/* AUTO-GENERATED by etl/make_demo_corpus.py — do not edit by hand.
   The ground truth for the demo corpus: which drug-reaction pairs were
   deliberately planted, from which quarter, at what excess rate.
   tests/02_detection_curve.sql scores the engine against this. */

USE aegis;

DROP TABLE IF EXISTS ground_truth_signals;
CREATE TABLE ground_truth_signals (
  ingredient        VARCHAR(128) NOT NULL,
  pt                VARCHAR(255) NOT NULL,
  emergence_quarter CHAR(6)      NOT NULL,
  peak_excess_rate  DECIMAL(6,4) NOT NULL,
  strength_tier     VARCHAR(16)  NOT NULL,
  PRIMARY KEY (ingredient, pt)
) ENGINE=InnoDB COMMENT='Planted associations in the synthetic demo corpus.';

INSERT INTO ground_truth_signals
  (ingredient, pt, emergence_quarter, peak_excess_rate, strength_tier) VALUES
  ('MONTELUKAST', 'SUICIDAL IDEATION', '2019Q2', 0.28, '1_strong'),
  ('MONTELUKAST', 'NIGHTMARE', '2019Q2', 0.24, '1_strong'),
  ('MONTELUKAST', 'DEPRESSION', '2019Q3', 0.22, '1_strong'),
  ('LEVOFLOXACIN', 'TENDON RUPTURE', '2019Q1', 0.3, '1_strong'),
  ('LEVOFLOXACIN', 'AORTIC ANEURYSM', '2020Q1', 0.18, '1_strong'),
  ('CIPROFLOXACIN', 'TENDON RUPTURE', '2019Q1', 0.22, '1_strong'),
  ('CANAGLIFLOZIN', 'DIABETIC KETOACIDOSIS', '2019Q1', 0.32, '1_strong'),
  ('CANAGLIFLOZIN', 'AMPUTATION', '2019Q4', 0.2, '1_strong'),
  ('FEBUXOSTAT', 'MYOCARDIAL INFARCTION', '2019Q1', 0.26, '1_strong'),
  ('ONDANSETRON', 'ELECTROCARDIOGRAM QT PROLONGED', '2020Q2', 0.24, '1_strong'),
  ('ONDANSETRON', 'TORSADE DE POINTES', '2020Q3', 0.16, '1_strong'),
  ('CLOZAPINE', 'AGRANULOCYTOSIS', '2019Q1', 0.34, '1_strong'),
  ('CLOZAPINE', 'MYOCARDITIS', '2020Q1', 0.2, '1_strong'),
  ('AMIODARONE', 'PULMONARY FIBROSIS', '2019Q1', 0.28, '1_strong'),
  ('ATORVASTATIN', 'RHABDOMYOLYSIS', '2019Q1', 0.18, '1_strong'),
  ('METFORMIN', 'LACTIC ACIDOSIS', '2019Q1', 0.2, '1_strong'),
  ('WARFARIN', 'GASTROINTESTINAL HAEMORRHAGE', '2019Q1', 0.24, '1_strong'),
  ('METHOTREXATE', 'PANCYTOPENIA', '2019Q1', 0.26, '1_strong'),
  ('ISOTRETINOIN', 'DEPRESSION', '2019Q1', 0.22, '1_strong'),
  ('VALPROATE', 'FOETAL MALFORMATION', '2019Q1', 0.3, '1_strong'),
  ('TRAMADOL', 'SEROTONIN SYNDROME', '2020Q1', 0.22, '1_strong'),
  ('TRAMADOL', 'RESPIRATORY DEPRESSION', '2020Q2', 0.18, '1_strong'),
  ('OMEPRAZOLE', 'CLOSTRIDIUM DIFFICILE COLITIS', '2019Q3', 0.16, '1_strong'),
  ('SITAGLIPTIN', 'PANCREATITIS', '2019Q2', 0.2, '1_strong'),
  ('HYDROXYCHLOROQUINE', 'ELECTROCARDIOGRAM QT PROLONGED', '2020Q2', 0.26, '1_strong'),
  ('ALLOPURINOL', 'STEVENS-JOHNSON SYNDROME', '2019Q1', 0.18, '1_strong'),
  ('VARENICLINE', 'SUICIDAL IDEATION', '2019Q1', 0.2, '1_strong'),
  ('APIXABAN', 'GASTROINTESTINAL HAEMORRHAGE', '2019Q2', 0.12, '2_moderate'),
  ('SERTRALINE', 'HYPONATRAEMIA', '2019Q3', 0.1, '2_moderate'),
  ('LEVOTHYROXINE', 'ATRIAL FIBRILLATION', '2019Q2', 0.09, '2_moderate'),
  ('PREDNISONE', 'PNEUMONIA', '2020Q1', 0.08, '2_moderate'),
  ('ADALIMUMAB', 'PNEUMONIA', '2019Q4', 0.075, '2_moderate'),
  ('CELECOXIB', 'MYOCARDIAL INFARCTION', '2019Q2', 0.06, '3_weak'),
  ('IBUPROFEN', 'GASTROINTESTINAL HAEMORRHAGE', '2019Q1', 0.055, '3_weak'),
  ('FUROSEMIDE', 'ACUTE KIDNEY INJURY', '2019Q3', 0.05, '3_weak'),
  ('INSULIN GLARGINE', 'HYPOGLYCAEMIA', '2019Q2', 0.045, '3_weak'),
  ('DULOXETINE', 'HEPATITIS', '2020Q1', 0.04, '3_weak'),
  ('AZITHROMYCIN', 'ELECTROCARDIOGRAM QT PROLONGED', '2019Q2', 0.03, '4_very_weak'),
  ('CLOPIDOGREL', 'HAEMORRHAGE', '2019Q3', 0.028, '4_very_weak'),
  ('TAMSULOSIN', 'HYPOTENSION', '2019Q2', 0.024, '4_very_weak'),
  ('ROSUVASTATIN', 'MYALGIA', '2019Q1', 0.02, '4_very_weak'),
  ('PANTOPRAZOLE', 'HYPONATRAEMIA', '2020Q1', 0.018, '4_very_weak'),
  ('GABAPENTIN', 'SOMNOLENCE', '2019Q2', 0.015, '4_very_weak');

SELECT COUNT(*) AS planted_pairs FROM ground_truth_signals;
