/* =============================================================================
   01_dimensions.sql — dimensional model, dimension tables
   -----------------------------------------------------------------------------
   Kimball star. Surrogate integer keys throughout, natural keys retained and
   uniquely constrained so reloads are idempotent.

   WHY A STAR AND NOT JUST QUERYING THE STAGING TABLES
   Two reasons, one analytical and one practical.
     Analytical: the 2x2 contingency table underlying every disproportionality
       statistic is a COUNT DISTINCT over cases, sliced by drug and reaction. A
       conformed grain makes that a single unambiguous count; against raw
       staging it is a nest of DISTINCTs whose correctness depends on the author
       remembering that a case appears once per version per drug per reaction.
     Practical: Power BI's VertiPaq engine compresses and relates a star far
       better than a snowflake or a wide flat table. Import mode on a proper
       star keeps the model responsive; the same data flattened does not.

   GRAIN DECLARATIONS ARE LOAD-BEARING. Each table below states its grain
   explicitly. Every reported number is only as trustworthy as the reader's
   confidence about what one row means.
   ========================================================================== */

USE aegis;

/* dim_date is generated by a recursive CTE spanning ~9,100 days. MySQL's
   default cte_max_recursion_depth is 1000, which aborts the generation at
   2005-09-27 — and would do so with an error rather than silently, but the
   error is easy to misread as a syntax problem. Raise it for this session. */
SET SESSION cte_max_recursion_depth = 20000;

/* ---------------------------------------------------------------------------
   dim_date — GRAIN: one row per calendar day.

   Keyed on the FDA RECEIPT date (fda_dt), not the event onset date (event_dt).
   This is a substantive analytical choice, not a convenience:
     * ~38% of cases have an absent or partial event_dt (quality gate DQ-008),
       so an onset-keyed series would silently drop over a third of the data,
       and drop it non-randomly — older and foreign reports are worse.
     * Disproportionality analysis asks "when could a regulator have known?",
       and a regulator can only know once the report has arrived. Receipt date
       is the decision-relevant clock.
   The cost is that reporting lag sits between onset and detection. That lag is
   real and is disclosed on the dashboard rather than assumed away.
   ------------------------------------------------------------------------ */
DROP TABLE IF EXISTS dim_date;
CREATE TABLE dim_date (
  date_key      INT          NOT NULL COMMENT 'YYYYMMDD',
  full_date     DATE         NOT NULL,
  year          SMALLINT     NOT NULL,
  quarter       TINYINT      NOT NULL,
  quarter_code  CHAR(6)      NOT NULL COMMENT 'e.g. 2024Q3 — joins to the quarterly signal series',
  quarter_start DATE         NOT NULL,
  month         TINYINT      NOT NULL,
  month_name    VARCHAR(12)  NOT NULL,
  day_of_month  TINYINT      NOT NULL,
  year_month_num INT         NOT NULL COMMENT 'YYYYMM',
  PRIMARY KEY (date_key),
  UNIQUE KEY uq_full_date (full_date),
  KEY ix_date_quarter (quarter_code),
  KEY ix_date_year (year)
) ENGINE=InnoDB COMMENT='GRAIN: one row per calendar day. Keyed on FDA receipt date.';

/* Generate 2003-01-01 .. 2027-12-31 with a recursive CTE. */
INSERT INTO dim_date
WITH RECURSIVE d AS (
  SELECT DATE('2003-01-01') AS dt
  UNION ALL
  SELECT dt + INTERVAL 1 DAY FROM d WHERE dt < '2027-12-31'
)
SELECT
  CAST(DATE_FORMAT(dt, '%Y%m%d') AS UNSIGNED),
  dt, YEAR(dt), QUARTER(dt),
  CONCAT(YEAR(dt), 'Q', QUARTER(dt)),
  MAKEDATE(YEAR(dt), 1) + INTERVAL (QUARTER(dt) - 1) QUARTER,
  MONTH(dt), MONTHNAME(dt), DAY(dt),
  CAST(DATE_FORMAT(dt, '%Y%m') AS UNSIGNED)
FROM d;

/* ---------------------------------------------------------------------------
   dim_drug — GRAIN: one row per standardised active ingredient.

   NOT one row per reported product string. That collapsing is the entire point
   of sql/03_reference/02_drug_normalisation.sql: 'SINGULAIR', 'Singulair 10mg'
   and 'MONTELUKAST SODIUM' are one exposure and must occupy one row, or the
   signal for that exposure is split across three under-powered fragments.
   ------------------------------------------------------------------------ */
DROP TABLE IF EXISTS dim_drug;
CREATE TABLE dim_drug (
  drug_key        INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ingredient      VARCHAR(128) NOT NULL,
  atc_class       VARCHAR(64)  NULL COMMENT 'coarse therapeutic class, for dashboard grouping',
  n_source_names  INT UNSIGNED NOT NULL COMMENT 'how many distinct raw strings collapsed here — the evidence that collapsing mattered',
  n_source_rows   BIGINT UNSIGNED NOT NULL,
  best_match_rung VARCHAR(20)  NOT NULL COMMENT 'highest-confidence rung used for this ingredient',
  PRIMARY KEY (drug_key),
  UNIQUE KEY uq_ingredient (ingredient),
  KEY ix_drug_class (atc_class)
) ENGINE=InnoDB COMMENT='GRAIN: one row per standardised active ingredient.';

/* ---------------------------------------------------------------------------
   dim_reaction — GRAIN: one row per MedDRA Preferred Term.
   MedDRA is a controlled vocabulary, so unlike the drug side this needs no
   fuzzy resolution. It is the clean half of the 2x2 table.
   ------------------------------------------------------------------------ */
DROP TABLE IF EXISTS dim_reaction;
CREATE TABLE dim_reaction (
  reaction_key INT UNSIGNED NOT NULL AUTO_INCREMENT,
  pt           VARCHAR(255) NOT NULL COMMENT 'MedDRA Preferred Term',
  soc          VARCHAR(96)  NOT NULL DEFAULT 'Unclassified' COMMENT 'System Organ Class',
  n_cases      BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (reaction_key),
  UNIQUE KEY uq_pt (pt),
  KEY ix_reaction_soc (soc)
) ENGINE=InnoDB COMMENT='GRAIN: one row per MedDRA Preferred Term.';

/* ---------------------------------------------------------------------------
   dim_patient — GRAIN: one row per distinct (age band, sex, weight band) combo.

   A junk dimension. Age is BANDED rather than stored raw for a specific
   correctness reason: FAERS age is meaningless without its unit column, and the
   classic corruption is '45 DEC' (45 decades) being read as 45 years. Banding
   at load time forces the unit conversion to happen exactly once, in one place,
   where it can be tested — rather than in every downstream query, where it
   would be done inconsistently or forgotten.
   ------------------------------------------------------------------------ */
DROP TABLE IF EXISTS dim_patient;
CREATE TABLE dim_patient (
  patient_key  INT UNSIGNED NOT NULL AUTO_INCREMENT,
  age_band     VARCHAR(16) NOT NULL,
  age_band_ord TINYINT     NOT NULL COMMENT 'explicit sort order; alphabetical would put 12-17 before 1-11',
  sex          VARCHAR(8)  NOT NULL,
  weight_band  VARCHAR(16) NOT NULL,
  PRIMARY KEY (patient_key),
  UNIQUE KEY uq_patient (age_band, sex, weight_band)
) ENGINE=InnoDB COMMENT='GRAIN: one row per distinct patient-attribute combination (junk dimension).';

/* ---------------------------------------------------------------------------
   dim_reporter — GRAIN: one row per distinct (qualification, country, report
   type) combination.

   Reporter qualification is not decoration. A signal carried by physician
   reports and one carried entirely by consumer reports have materially
   different evidential weight, and litigation-driven reporting surges show up
   as lawyer-sourced reports. Being able to stratify on this is what separates
   a real signal from a media artefact.
   ------------------------------------------------------------------------ */
DROP TABLE IF EXISTS dim_reporter;
CREATE TABLE dim_reporter (
  reporter_key   INT UNSIGNED NOT NULL AUTO_INCREMENT,
  occp_cod       VARCHAR(16) NOT NULL,
  occp_desc      VARCHAR(48) NOT NULL,
  is_health_prof TINYINT(1)  NOT NULL,
  country        VARCHAR(64) NOT NULL,
  is_domestic_us TINYINT(1)  NOT NULL,
  rept_cod       VARCHAR(16) NOT NULL,
  PRIMARY KEY (reporter_key),
  UNIQUE KEY uq_reporter (occp_cod, country, rept_cod)
) ENGINE=InnoDB COMMENT='GRAIN: one row per distinct reporter-attribute combination.';

SELECT 'dimension tables created' AS status,
       (SELECT COUNT(*) FROM dim_date) AS dim_date_rows;
